case: 2d

dataset:
  type: GraphST2D
  data_file: data/2D_data.h5ad
  val_proportion: 0.2
  keep_ratio: True
  n_neighbors: 4
  require_coordnorm: true

pipeline:
  embedder:
    model: GAE
    dim_hidden: [2048, 512, 128]
    dim_latent: 64

  optimization:
    seed: 8848
    epochs: 1000
    lr: 1e-5
    val_freq: 50
    logs: logs/GAE-2D/${case}
    batch_size: 512
  
  predict_mode: all
  embedded_data: embedded-all.h5ad
