case: 2d

dataset:
  type: ST2D
  data_file: logs/GAE-2D/${case}/lightning_logs/version_0/embedded-all.h5ad
  val_proportion: 0.2
  keep_ratio: True
  require_coordnorm: False

pipeline:
  target: embeddings
  
  prediction:
    ckpt: 'logs/GAE+FFN-2D/${case}/lightning_logs/version_0/checkpoints/last.ckpt'

  inr:
    model: FFN
    num_hidden_layers: 3
    num_hidden_features: 2048 
    phase: 1000 # number of epoches in the INR pretraining phase, after this phase the decoder will be trained.
    decoder:
      ckpt: logs/GAE-2D/${case}/lightning_logs/version_0/checkpoints/last.ckpt
      recon_loss: True
      finetune: True
      
  optimization:
    seed: 8848
    epochs: 2000
    lr: 1e-4
    val_freq: 200
    logs: logs/GAE+FFN-2D/${case}
    batch_size: 8192
  
  predict_mode: custom
  custom_coords_file: data/preprocessed_data/custom_coords_2d_norm.npy
  reconstructed_data: reconstructed-custom_2d.h5ad